apiVersion: v1
kind: Service
metadata:
  name: apppy-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3030
      nodePort: 30300
  type: NodePort
